export default {
    'themeforest/site-templates': 4,
    'themeforest/wordpress': 12,
    'themeforest/cms-themes': 10,
    'themeforest/ecommerce': 15,
    'themeforest/blogging': 5,
    'themeforest/marketing': 4,
    'themeforest/forums': 4,
    'themeforest/muse-templates': 4,
    'themeforest/static-site-generators': 4,
    'themeforest/jamstack': 4,
    'themeforest/courses': 1,
    'themeforest/template-kits': 5,
    'themeforest/ui-templates': 2,

    'codecanyon/javascript': 2,
    'codecanyon/php-scripts': 5,
    'codecanyon/net': 4,
    'codecanyon/wordpress': 5,
    'codecanyon/plugins': 4,
    'codecanyon/css': 1,
    'codecanyon/html5': 3,
    'codecanyon/mobile': 4,
    'codecanyon/apps': 2,
    'codecanyon/skins': 3,
    'codecanyon/edge-animate-templates': 2,

    'videohive/after-effects-project-files': 6,
    'videohive/premiere-pro-templates': 4,
    'videohive/davinci-resolve-templates': 4,
    'videohive/apple-motion-templates': 4,
    'videohive/motion-graphics': 3,
    'videohive/stock-footage': 3,
    'videohive/cinema-4d-templates': 6,
    'videohive/add-ons': 4,

    'audiojungle/music': 4,
    'audiojungle/music-packs': 12,
    'audiojungle/music-kits': 8,
    'audiojungle/sound': 0,
    'audiojungle/source-files': 7,
    'audiojungle/logos-idents': 2,

    'graphicriver/graphics': 1,
    'graphicriver/print-templates': 1,
    'graphicriver/epublishing': 3,
    'graphicriver/textures': 1,
    'graphicriver/vectors': 1,
    'graphicriver/infographics': 1,
    'graphicriver/add-ons': 1,
    'graphicriver/isolated-objects': 1,
    'graphicriver/icons': 1,
    'graphicriver/presentation-templates': 3,
    'graphicriver/fonts': 2,
    'graphicriver/web-elements': 1,
    'graphicriver/logo-templates': 5,
    'graphicriver/t-shirts': 2,
    'graphicriver/game-assets': 1,

    'photodune/misc': 1,

    '3docean/animation-data': 2,
    '3docean/3d-models': 3,
    '3docean/render-setups': 3,
    '3docean/materials-and-shaders': 1,
    '3docean/cg-textures': 1,
    '3docean/2d-concepts': 2,
    '3docean/scripts-and-plugins': 4,
};
